title: Lakmal Siriwardhana | Portfolio
description: Low-level enough to trigger a blue screen. High-level enough to write a beautiful error page for it.
theme: jekyll-theme-minimal
include:
  - _assets
